version: '2'
services:
  redis:
    container_name: slamby_redis
    image: redis:3.0
    restart: always
    cpu_shares: 512
    volumes:
      - /usr/share/redis/data:/data
  elasticsearch:
    container_name: slamby_elasticsearch
    restart: always
    image: slamby/elasticsearch:1.0
    volumes:
      - /usr/share/elasticsearch/data:/usr/share/elasticsearch/data
    oom_score_adj: -1000
    cpu_shares: 512
  slambyapi:
    container_name: slamby_api
    restart: always
    image: slamby/slamby.api:1.7.0
    volumes:
      - /usr/share/slamby:/Slamby
    depends_on:
      - elasticsearch
      - redis
    links:
      - elasticsearch
      - redis
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "3"
    oom_score_adj: -1000
    cpu_shares: 1024
  nginx:
    container_name: slamby_nginx
    image: slamby/nginx:1.0
    restart: always
    ports:
      - "80:80"
    depends_on:
      - slambyapi
    links:
      - slambyapi
    cpu_shares: 512